noun1 = input("Podaj pierwszy rzeczownik: ")
noun2 = input("Podaj drugi rzeczownik: ")
plural_noun1 = input("Podaj rzeczownik liczby mnogiej: ")
adjective1 = input("Podaj pierwszy przymiotnik: ")
adjective2 = input("Podaj drugi przymiotnik: ")
adjective3 = input("Podaj trzeci przymiotnik: ")
adverb = input("Podaj przysłowek: ")
plural_noun2 = input("Podaj drugi rzeczownik liczby mnogiej: ")
adjective4 = input("Podaj czwarty przymiotnik: ")
adjective5 = input("Podaj piąty przymiotnik: ")

print("Our dining " + noun1 + " used to be a war " + noun2)
print("I thought the battles about correct table " + plural_noun1 + " would never end.")
print("It was us kids versus Mom, and it seemd like a fight that would last to the " + adjective1 + " end.")
print("But tonight Dad finally declared a " + adjective2 + " truce,")
print("and we negotiated a " + adjective3 + " peace.")
print("Mom promised to no longer get " + adverb + " upset")
print("and shoot us dirty " + plural_noun2 + " and make " + adjective4 + " remarks when we do " + adjective5 + " thing she doesn't like")

